### ISSUE TITLE
yolact_edge - need to pass detect = [ ] as integer not string class labels

### ISSUE THREAD

**Issue by tappyness1** [aisingapore/PeekingDuck#749]
For Object Detection, to pass the .Node, we use detect = ["class_name0", "class_name1", ..., "class_nameN"]. However, for yolact, we will need to use detect = [0, 1, ..., N].

yolact_edge: 
![image](https://user-images.githubusercontent.com/19956863/229412433-961ab6c8-32f2-4c8f-a6a1-efd4b2a31029.png)

yolov4-tiny:
![image](https://user-images.githubusercontent.com/19956863/229412576-5b12c2aa-a35d-46bb-8e22-1df025729dbb.png)

[Request] To align on which to use - integer index or class name as string

**Comment by ongtw** [comment]
Hi, the latest release of PeekingDuck is able to accept class names for `yolact_edge`:
![image](https://user-images.githubusercontent.com/13075447/230832020-bfb2b43f-cf03-4333-afd1-cb02a8350359.png)
As can be seen above, the `person` got converted internally to id `0`.
Please update your PeekingDuck to the latest version.
